# site properties and page defaults
title: TJU-VEX
subtitle: 
description: 同济大学VEX机器人实验室
header: images/background.jpg
footer: images/background.jpg
proofer: false
slogan:
  - "同济大学VEX机器人实验室"
  - "TJU VEX Robotics Lab"
  - "VEX Robotics Lab of Tongji University"

# site social media and other links
links:
  email: 13605046617@163.com
  github: hyxtj
  bilibili: https://space.bilibili.com/3546375585270436

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "news"
    values:
      layout: news

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  news:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
